language: python
python:
  - "3.6"
before_install:
  - pip install --upgrade pip
install:
  - pip install -r requirements.txt
  - pip install -r requirements_test.txt
  - pip install coveralls
script:
  make test
after_success:
  coveralls
